services:
  yocto:
    build:
      context: ./yocto/
    hostname: yocto
    tty: true
    stdin_open: true
    volumes:
      - ./yocto/workspace/:/workspace/
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
  buildroot:
    build:
      context: ./buildroot/
    hostname: buildroot
    tty: true
    stdin_open: true
    volumes:
      - ./buildroot/workspace/:/workspace/
    restart: unless-stopped
  ubuntu:
    build:
      context: ./ubuntu/
    hostname: ubuntu
    tty: true
    stdin_open: true
    volumes:
      - ./ubuntu/workspace/:/workspace/
    restart: unless-stopped
